[package]
name = "audio_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.9", features = [ "derive" ] }
image = "0.24"
winit = "0.26"
glam = { version = "0.20", features = [ "bytemuck", "rand"] }
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2"
anyhow = "1.0"

rustfft = "6.0"
rodio = "0.15"
